language: generic

sudo: required

services:
    - docker

before_install:

script:

after_success:
    - docker build -t yoon7548/docker-backend-campfire ./backend
    - docker build -t yoon7548/docker-nginx-campfire ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

    - docker push yoon7548/docker-backend-campfire
    - docker push yoon7548/docker-nginx-campfire

deploy:
    provider: elasticbeanstalk
    region: 'ap-northeast-2'
    app: 'campfire-app'
    env: 'Campfireapp-env'
    bucket_name: elasticbeanstalk-ap-northeast-2-792971416589
    bucket_path: 'campfire-app'
    on:
        branch: main

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY